# 00_Config.R - GÜNCELLENMİŞ HAL (Asenkron İşlemler için Paketler Eklendi)

library(shiny)
library(shinythemes)
library(shinyjs)
library(shinyWidgets)
library(dplyr)
library(tidyr)
library(lubridate)
library(stringr)

library(readxl)
library(openxlsx)
library(readr)
library(janitor)
library(ggplot2)
library(DT)
library(scales)
library(forcats)
library(DBI)      
library(pool)     
library(config)   
library(bcrypt)
library(RMariaDB)
library(config)
library(DBI)
library(prophet)
library(purrr)

library(future)          
library(promises)        
library(shinycssloaders) 
