name: lintr

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '31 2 * * 1'

permissions:
  contents: read

jobs:
  lintr:
    name: Run lintr scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Cache renv packages
        uses: actions/cache@v4
        with:
          path: ~/.local/share/renv
          key: ${{ runner.os }}-${{ hashFiles('renv.lock') }}
          restore-keys: ${{ runner.os }}-

      - name: Restore renv packages
        shell: Rscript {0}
        run: |
          options(renv.consent = TRUE)
          renv::restore()
        env:
          R_PROFILE_USER: ".github/workflows/empty.Rprofile"

      - name: Run lintr
        run: lintr::lint_dir(".", linters = lintr::default_linters)
        shell: Rscript {0}
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: lintr-results.sarif
          wait-for-processing: true