# ... (dosyanın başındaki yorumlar aynı kalır) ...

name: lintr

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '31 2 * * 1'

permissions:
  contents: read

jobs:
  lintr:
    name: Run lintr scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ===================================================================
      #               >>> DEĞİŞİKLİK BURADA BAŞLIYOR <<<
      # ===================================================================
      # R'ı kurarken .Rprofile'ı çalıştırmasını engelliyoruz.
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true # Paketleri daha hızlı kurmasını sağlar

      # lintr'ı kurarken de .Rprofile'ı çalıştırmasını engelliyoruz.
      - name: Setup lintr
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: lintr
        env:
          R_PROFILE_USER: ".github/workflows/empty.Rprofile" # Boş bir profil dosyası göstererek bizimkini ezmesini sağlıyoruz
      # ===================================================================

      - name: Run lintr
        run: lintr::sarif_output(lintr::lint_dir("."), "lintr-results.sarif")
        shell: Rscript {0}
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: lintr-results.sarif
          wait-for-processing: true```