# lintr.yml - Her adımda renv'i aktive eden nihai çözüm

name: lintr

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  lintr:
    name: Run lintr scanning
    runs-on: ubuntu-latest
    env:
      R_PROFILE_USER: ".github/workflows/empty.Rprofile"
      RENV_CONFIG_PAK_ENABLED: "FALSE"

    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install renv
        run: install.packages("renv", repos = "https://cloud.r-project.org")
        shell: Rscript {0}

      - name: Cache renv packages
        uses: actions/cache@v4
        with:
          path: ~/.local/share/renv
          key: ${{ runner.os }}-${{ hashFiles('renv.lock') }}
          restore-keys: ${{ runner.os }}-

      - name: Restore renv packages
        run: renv::restore()
        shell: Rscript {0}

      # ===================================================================
      #               >>> DEĞİŞİKLİK BURADA <<<
      # ===================================================================
      # lintr'ı çalıştırmadan ÖNCE, renv'i bu yeni R oturumu için aktive ediyoruz.
      - name: Run lintr
        shell: Rscript {0}
        run: |
          source("renv/activate.R")
          lintr::lint_dir(".", linters = lintr::default_linters)
          lintr::sarif_output(lintr::lint_dir("."), "lintr-results.sarif") # sarif dosyasını oluştur
      # ===================================================================
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: lintr-results.sarif
          wait-for-processing: true